// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHVojmMgo0oY2sNdWTb7KHVFUxt9GdXBk',
    appId: '1:181751243438:web:06ab8f119c6abd8defc33f',
    messagingSenderId: '181751243438',
    projectId: 'fir-flutter-codelab-fc054',
    authDomain: 'fir-flutter-codelab-fc054.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-fc054.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsYeIxz06ZVzAvli-ykAMHyjOIMG3b0T4',
    appId: '1:181751243438:android:ca4b38c6da953f28efc33f',
    messagingSenderId: '181751243438',
    projectId: 'fir-flutter-codelab-fc054',
    storageBucket: 'fir-flutter-codelab-fc054.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8EGBOpqMde-SzPTG4PMG0k_W9kgg4xWg',
    appId: '1:181751243438:ios:762a403e3b25ebf6efc33f',
    messagingSenderId: '181751243438',
    projectId: 'fir-flutter-codelab-fc054',
    storageBucket: 'fir-flutter-codelab-fc054.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8EGBOpqMde-SzPTG4PMG0k_W9kgg4xWg',
    appId: '1:181751243438:ios:762a403e3b25ebf6efc33f',
    messagingSenderId: '181751243438',
    projectId: 'fir-flutter-codelab-fc054',
    storageBucket: 'fir-flutter-codelab-fc054.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
